"""empty message

Revision ID: 061e037d1cb8
Revises: ca9e1f5aef8c
Create Date: 2022-01-28 16:08:47.178836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061e037d1cb8'
down_revision = 'ca9e1f5aef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countrys',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countrys')
    # ### end Alembic commands ###
