"""Add phone in Contact

Revision ID: 45f7e765b9fe
Revises: ff03d4a40136
Create Date: 2022-02-01 17:49:39.789456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f7e765b9fe'
down_revision = 'ff03d4a40136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'phone')
    # ### end Alembic commands ###
