"""empty message

Revision ID: 49ee153853fe
Revises: 4fdb802cc7bc
Create Date: 2022-01-28 10:39:29.105618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ee153853fe'
down_revision = '4fdb802cc7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('country', sa.String(length=50), nullable=True))
    op.drop_column('company', 'contry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('contry', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('company', 'country')
    # ### end Alembic commands ###
