"""empty message

Revision ID: b491023a992a
Revises: b53f21a3f8fc
Create Date: 2022-01-26 20:51:49.811827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b491023a992a'
down_revision = 'b53f21a3f8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('contry', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'contry')
    # ### end Alembic commands ###
